// pages/blog/_id/write.vue
<template>
  <div class="m-3">
    <b-form-group>
      <b-form-input v-model="blogArticle.title" :placeholder="$t('blogArticle.title')"></b-form-input>
    </b-form-group>
    <b-form-group>
      <editor ref="toastuiEditor" />
    </b-form-group>
    <div class="text-right">
      <b-button @click="createAction">{{ $t("blogArticle.write") }}</b-button>
      <b-button>{{ $t("blogArticle.cancel") }}</b-button>
    </div>
  </div>
</template>

<script>
import blogMixin from "@/assets/blog/blog.js";
import blogArticleMixin from "@/assets/blog/blogArticle.js";

import "codemirror/lib/codemirror.css";
import "@toast-ui/editor/dist/toastui-editor.css";

import { Editor } from "@toast-ui/vue-editor";

export default {
  mixins: [blogMixin, blogArticleMixin],
  components: {
    editor: Editor
  },
  data() {
    return {
      blogArticle: {
        title: "",
        content: ""
      }
    };
  },
  watch: {},
  // asyncData({ params }) {
  //   console.log(params);
  // },
  methods: {
    createAction() {
      this.blogArticle.content = this.$refs.toastuiEditor.invoke("getHtml");
      this.create(this.blogArticle)
        .then(data => {
          if (data !== undefined) {
            this.moveUserBlogListView();
          }
        })
        .catch(this.commonErrorHandler);
    }
  },
  mounted() {}
};
</script>

<style></style>

// bluesky-project-front-sveltekit/src/routes/board/[alias]/write/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Editor from '@toast-ui/editor';
	import '@toast-ui/editor/dist/toastui-editor.css';
	import { page } from '$app/stores';
	import { boardClient, boardArticleClient, type Board } from '$lib/board';

	let board: Board;
	let title = '';
	let editor: Editor;

	onMount(async () => {
		board = await boardClient.findByAlias({ alias: $page.params.alias });
		console.log('board : ' + board.boardId);
		editor = new Editor({
			el: document.querySelector('#editor')
		});
	});
	function create() {
		console.log('editor : ', editor.getMarkdown());
		console.log('page : ', $page.params.alias);
		boardArticleClient.create({
			boardId: board.boardId,
			title: title,
			content: editor.getMarkdown()
		});
	}
</script>

<div>
	<div>
		<input type="text" id="title" bind:value={title} placeholder="제목" />
	</div>
	<div id="editor" />
	<div>
		<button on:click={create}>쓰기</button>
	</div>
</div>
