// components/BlueskyNavBar.vue
<template>
  <b-navbar toggleable="md" type="dark" variant="dark">
    <b-navbar-toggle target="nav_collapse"></b-navbar-toggle>

    <b-navbar-brand :to="'/'">Bluesky</b-navbar-brand>

    <b-collapse is-nav id="nav_collapse">
      <b-navbar-nav>
        <b-nav-item :to="'/blog'">Blog</b-nav-item>
        <b-nav-item :to="'/bookkeeping/index'">Bookkeeping</b-nav-item>
      </b-navbar-nav>

      <b-navbar-nav class="ml-auto">
        <b-nav-form v-if="!loginInfo">
          <b-form-input class="mr-1" name="username" :placeholder="$t('username')" />
          <b-form-input class="mr-1" type="password" name="password" :placeholder="$t('password')" />
          <b-button class="mr-2" type="submit">{{ $t("login") }}</b-button>
          <b-button class="mr-1" href="/oauth2/authorization/google">
            <font-awesome-icon :icon="{ prefix: 'fab', iconName: 'google' }" />
          </b-button>
          <b-button class="mr-1" href="/oauth2/authorization/facebook">
            <font-awesome-icon :icon="{ prefix: 'fab', iconName: 'facebook' }" />
          </b-button>
          <b-button class="mr-1" href="/oauth2/authorization/github">
            <font-awesome-icon :icon="{ prefix: 'fab', iconName: 'github' }" />
          </b-button>
          <b-button class="mr-1" href="/oauth2/authorization/battlenet">
            <font-awesome-icon icon="bold" />
          </b-button>
        </b-nav-form>

        <b-nav-form v-if="loginInfo" action="/logout" method="post">
          <b-nav-text class="mr-sm-2">{{ loginInfo.name }}</b-nav-text>
          <b-button size="sm" type="submit">{{ $t('logout') }}</b-button>
        </b-nav-form>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>

<script>
import { mapState, mapMutations } from "vuex";
import commonMixin from "@/components/common.js";

export default {
  name: "BlueskyNavBar",
  computed: {
    ...mapState({
      loginInfo: state => state.loginInfo.loginInfo
    })
  },
  mixins: [commonMixin],
  methods: {
    ...mapMutations({ setLoginInfo: "loginInfo/setLoginInfo" })
  },
  mounted: function() {
    var _this = this;
    console.log("AASDFASDF", this);
    fetch("/api/user/loginInfo.json", {
      method: "GET",
      headers: {
        "Content-type": "application/json"
      }
    })
      .then(this.commonResponseData)
      .then(data => {
        console.log("this : ", this);
        this.setLoginInfo(data);
        return data;
      });
    // this.$http.get("/api/user/loginInfo").then(function(response) {
    //   _this.setLoginInfo(response.data);
    // });
  }
};
</script>

// bluesky-project-front-sveltekit/src/lib/BlueskyNavBar.svelte
<script lang="ts">
	import {
		Button,
		Collapse,
		Navbar,
		NavbarToggler,
		NavbarBrand,
		Nav,
		NavItem,
		NavLink,
		Dropdown,
		DropdownToggle,
		DropdownMenu,
		DropdownItem
	} from 'sveltestrap';
	import { session } from '$app/stores';

	let isOpen = false;

	function handleUpdate(event: any) {
		isOpen = event.detail.isOpen;
	}

	// async function getUserInfo() {
	// 	return fetch('/api/user/loginInfo', {
	// 		method: 'GET',
	// 		headers: {
	// 			'Content-Type': 'application/json'
	// 			// 'Content-Type': 'application/x-www-form-urlencoded',
	// 		}
	// 	}).then((response) => response.json());
	// }

	//const userInfo = getUserInfo();
	//console.log(userInfo);
</script>

<Navbar color="light" light expand="md">
	<NavbarBrand href="/">Bluesky</NavbarBrand>
	<NavbarToggler on:click={() => (isOpen = !isOpen)} />
	{JSON.stringify($session)}
	<Collapse {isOpen} navbar expand="md" on:update={handleUpdate}>
		<Nav navbar>
			<NavItem>
				<NavLink href="/blog">Blog</NavLink>
			</NavItem>
			<NavItem>
				<NavLink href="/bookkeeping">Bookkeeping</NavLink>
			</NavItem>
		</Nav>
		<Nav class="ms-auto" navbar>
			<NavItem>
				<NavLink href="/oauth2/authorization/google">
					<Button outline class="fa-brands fa-google" />
				</NavLink>
			</NavItem>
			<NavItem>
				<NavLink href="/oauth2/authorization/facebook">
					<Button outline class="fa-brands fa-facebook" />
				</NavLink>
			</NavItem>
			<NavItem>
				<NavLink href="/oauth2/authorization/github">
					<Button outline class="fa-brands fa-github" />
				</NavLink>
			</NavItem>
			<NavItem>
				<NavLink href="/oauth2/authorization/battlenet">
					<Button outline class="fa-brands fa-battle-net" />
				</NavLink>
			</NavItem>
		</Nav>
	</Collapse>
</Navbar>
